[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "mvn", args = ["fmt:format"] }
auto-format = false
roots = ["pom.xml", "build.gradle", ".git"]
language-servers = ["jdtls"]  
scope = "source.java"
file-types = ["java"]

[[language]]
name = "scala"
file-types = ["scala", "sbt"]
auto-format = true

[[language]]
name = "typescript"
auto-format = false
